//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMISDayLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentStatusHistory
    {
        public int ComponentStatusHistory1 { get; set; }
        public int ComponentId { get; set; }
        public string Oldstatus { get; set; }
        public string NewStatus { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string ChangedByUserName { get; set; }
        public int ChangedByUserId { get; set; }
    
        public virtual Component Component { get; set; }
    }
}
