//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMISDayLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View2
    {
        public string ComponentName { get; set; }
        public int ComponentId { get; set; }
        public string Status { get; set; }
        public int DailyDeveloperTaskLogId { get; set; }
        public string Task { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TimeStart { get; set; }
        public Nullable<int> TimeEnd { get; set; }
        public string ViewName { get; set; }
        public string Remark { get; set; }
        public string DeveloperName { get; set; }
        public Nullable<int> Age { get; set; }
        public string PhoneNumber { get; set; }
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public int ControllerId { get; set; }
        public string ControllerName { get; set; }
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
    }
}
